-- Insert London Areas Data
INSERT INTO london_areas (name, postcode, description, investment_perspective, market_analysis, positive_aspects, negative_aspects, average_price, price_growth_percentage, nearest_tube_station) VALUES
('Bayswater', 'W2', 'Elegant Victorian garden squares with excellent transport links and international dining scene.', 'Strong rental demand from young professionals. Hyde Park proximity adds premium. Crossrail impact positive.', 'Properties range from £800k studio flats to £5M+ houses. Rental yields 3-4%. High international buyer interest.', ARRAY['Hyde Park proximity', 'Excellent transport', 'International community', 'Period architecture', 'Strong rental market'], ARRAY['Tourist crowds', 'Limited parking', 'High service charges', 'Short-term rental competition'], 1250000, 4.2, 'Bayswater, Paddington'),

('Maida Vale', 'W9', 'Tree-lined streets with white stucco mansion blocks and canal-side living. Popular with media professionals.', 'Consistent growth area with strong fundamentals. Little Venice location premium. Good long-term prospects.', 'Mix of mansion flats and period houses. Average £900k-£2.5M. Stable rental market with 3.5% yields.', ARRAY['Little Venice canals', 'Period mansion blocks', 'Village feel', 'Good schools nearby', 'Stable market'], ARRAY['Limited new development', 'Flood risk areas', 'Expensive parking', 'Council tax band variations'], 1100000, 3.8, 'Maida Vale, Warwick Avenue'),

('St Johns Wood', 'NW8', 'Prestigious residential area with cricket ground proximity, excellent schools and embassy quarter location.', 'Prime London location with strong capital growth. International school proximity drives demand.', 'Premium market £1.5M-£10M+. Strong international buyer base. Rental yields 2.5-3.5%.', ARRAY['Lords Cricket Ground', 'American School nearby', 'Embassy quarter', 'Low crime', 'Excellent transport'], ARRAY['Very expensive', 'Limited starter homes', 'Parking restrictions', 'High council tax'], 2250000, 5.1, 'St Johns Wood, Baker Street'),

('Queens Park', 'NW6', 'Trendy area with young families, excellent local schools, independent shops and strong community feel.', 'Rapid gentrification with strong growth potential. Family market driving demand. Good value vs central areas.', 'Victorian terraces £800k-£2M. Strong rental demand from families. Yields 3.5-4.5%.', ARRAY['Excellent schools', 'Family-friendly', 'Independent shops', 'Community feel', 'Growth potential'], ARRAY['Gentrification displacement', 'Limited commercial area', 'Parking pressure', 'School catchment competition'], 950000, 6.2, 'Queens Park, Kilburn Park'),

('Kilburn', 'NW6', 'Diverse multicultural area with excellent transport links, developing food scene and good value properties.', 'Emerging area with regeneration potential. Crossrail will boost accessibility. Good entry-level pricing.', 'Mixed housing stock £500k-£1.5M. Strong rental yields 4-5%. First-time buyer market active.', ARRAY['Affordable by London standards', 'Excellent transport', 'Cultural diversity', 'Developing area', 'High rental yields'], ARRAY['Some rough areas', 'Limited green space', 'Traffic congestion', 'Gentrification concerns'], 650000, 4.8, 'Kilburn, Kilburn Park'),

('Kensal Green', 'NW10', 'Up-and-coming area with canal-side developments, creative community and improving transport links.', 'Regeneration hotspot with significant upside potential. HS2 and Crossrail accessibility improvements.', 'Rapid price growth £600k-£1.8M. New developments driving market. Yields 4-6%.', ARRAY['Regeneration area', 'Creative community', 'Transport improvements', 'Canal location', 'Growth potential'], ARRAY['Construction disruption', 'Limited amenities', 'Industrial heritage', 'Uneven development'], 750000, 7.1, 'Kensal Green, Kensal Rise'),

('Ladbroke Grove', 'W10', 'Vibrant multicultural area famous for Notting Hill Carnival, antique markets and diverse dining scene.', 'Established area with tourist appeal. Portobello Market proximity adds character premium.', 'Victorian terraces and mansion flats £700k-£3M. Tourist rental potential. Yields 3.5-4.5%.', ARRAY['Portobello Market', 'Cultural scene', 'Transport links', 'Period properties', 'Tourist appeal'], ARRAY['Carnival disruption', 'Tourist crowds', 'Parking issues', 'Social housing mix'], 880000, 3.9, 'Ladbroke Grove, Westbourne Park');

-- Insert Properties Data (15 properties: 5 houses, 5 flats, 5 commercial)

-- HOUSES (5)
INSERT INTO properties (listing_type, status, title, description, price, price_qualifier, property_type, bedrooms, bathrooms, receptions, square_footage, address_line1, address_line2, postcode, area_id, tenure, council_tax_band, energy_rating, year_built, features, amenities, images, floor_plan, viewing_arrangements, agent_contact) VALUES

('sale', 'active', 'Stunning 4-Bedroom Victorian Terrace in Bayswater', 'Beautifully restored Victorian terrace house offering elegant family living across four floors. Features include period details, modern kitchen, landscaped garden, and off-street parking. Close to Hyde Park and excellent schools.', 285000000, 'guide_price', 'house', 4, 3, 2, 2100, '42 Gloucester Terrace', '', 'W2 3HB', 1, 'freehold', 'G', 'C', 1885, ARRAY['period_features', 'garden', 'parking', 'high_ceilings', 'modern_kitchen', 'wooden_floors'], ARRAY['Hyde Park 2 mins', 'Paddington Station 5 mins', 'Local shops', 'Restaurants'], ARRAY['/images/house1-1.jpg', '/images/house1-2.jpg', '/images/house1-3.jpg'], '/images/house1-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958'),

('sale', 'active', 'Elegant 5-Bedroom Family Home in St Johns Wood', 'Magnificent family residence on a prestigious tree-lined street. This beautifully appointed house offers spacious accommodation, private garden, garage, and is perfectly positioned near Lords Cricket Ground and excellent schools.', 425000000, 'offers_over', 'house', 5, 4, 3, 3200, '15 Grove End Road', '', 'NW8 9LL', 3, 'freehold', 'H', 'D', 1920, ARRAY['garden', 'parking', 'period_features', 'high_ceilings', 'modern_kitchen', 'ensuite_bathroom'], ARRAY['Lords Cricket Ground', 'American School nearby', 'Regents Park', 'St Johns Wood High Street'], ARRAY['/images/house2-1.jpg', '/images/house2-2.jpg', '/images/house2-3.jpg'], '/images/house2-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958'),

('sale', 'active', 'Charming 3-Bedroom Victorian House in Queens Park', 'Beautifully presented Victorian terraced house in the heart of Queens Park. Retains original character with modern updates throughout. South-facing garden, period features, and close to excellent local schools and transport.', 135000000, 'guide_price', 'house', 3, 2, 2, 1450, '28 Kempe Road', '', 'NW6 6SB', 4, 'freehold', 'E', 'C', 1895, ARRAY['period_features', 'garden', 'wooden_floors', 'high_ceilings', 'recently_renovated'], ARRAY['Queens Park School', 'Local shops', 'Salusbury Road', 'Queens Park'], ARRAY['/images/house3-1.jpg', '/images/house3-2.jpg', '/images/house3-3.jpg'], '/images/house3-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958'),

('rental', 'active', 'Beautiful 4-Bedroom House Available for Rent in Maida Vale', 'Stunning recently refurbished family house in sought-after Maida Vale location. Four bedrooms, modern kitchen, private garden, and parking. Close to Little Venice and excellent transport connections.', 650000, NULL, 'house', 4, 3, 2, 1850, '67 Clifton Gardens', '', 'W9 1DT', 2, 'leasehold', 'F', 'B', 1910, ARRAY['garden', 'parking', 'recently_renovated', 'modern_kitchen', 'period_features'], ARRAY['Little Venice', 'Warwick Avenue Station', 'Canal walks', 'Local amenities'], ARRAY['/images/house4-1.jpg', '/images/house4-2.jpg', '/images/house4-3.jpg'], '/images/house4-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958'),

('sale', 'under_offer', 'Period 3-Bedroom House with Development Potential in Kensal Green', 'Characterful Victorian terrace house requiring modernisation. Excellent opportunity for renovation with scope to extend (STPP). Large garden, period features intact, and in up-and-coming Kensal Green location.', 89500000, 'guide_price', 'house', 3, 1, 2, 1200, '124 Chevening Road', '', 'NW10 3LR', 6, 'freehold', 'D', 'E', 1890, ARRAY['period_features', 'garden', 'high_ceilings', 'original_features'], ARRAY['Kensal Green Station', 'Local shops', 'Canal nearby', 'Regeneration area'], ARRAY['/images/house5-1.jpg', '/images/house5-2.jpg', '/images/house5-3.jpg'], '/images/house5-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958');

-- FLATS (5)
INSERT INTO properties (listing_type, status, title, description, price, price_qualifier, property_type, bedrooms, bathrooms, receptions, square_footage, address_line1, address_line2, postcode, area_id, tenure, council_tax_band, energy_rating, year_built, features, amenities, images, floor_plan, viewing_arrangements, agent_contact, rent_period, furnished, available_from, minimum_tenancy, deposit) VALUES

('sale', 'active', 'Luxury 2-Bedroom Apartment with Balcony in Bayswater', 'Contemporary apartment in prestigious portered building. Two double bedrooms, modern kitchen, reception room, balcony overlooking garden square. Lift access, concierge, and prime Hyde Park location.', 112500000, 'guide_price', 'flat', 2, 2, 1, 900, 'Flat 15, Lancaster Gate Mansions', 'Lancaster Gate', 'W2 3LN', 1, 'leasehold', 'F', 'B', 2018, ARRAY['balcony', 'lift', 'concierge', 'modern_kitchen', 'ensuite_bathroom', 'air_conditioning'], ARRAY['Hyde Park opposite', 'Lancaster Gate Station', 'Restaurants', 'Shopping'], ARRAY['/images/flat1-1.jpg', '/images/flat1-2.jpg', '/images/flat1-3.jpg'], '/images/flat1-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', NULL, NULL, NULL, NULL, NULL),

('rental', 'active', 'Spacious 1-Bedroom Flat for Rent in Kilburn', 'Well-presented one-bedroom apartment in converted Victorian house. Open-plan living, modern kitchen, good storage, and excellent transport links. Perfect for young professional.', 175000, NULL, 'flat', 1, 1, 1, 550, 'Flat 3, 89 Kilburn High Road', '', 'NW6 6JE', 5, 'leasehold', 'C', 'C', 1890, ARRAY['modern_kitchen', 'recently_renovated', 'good_storage'], ARRAY['Kilburn Station', 'High Road shops', 'Buses to central London', 'Local amenities'], ARRAY['/images/flat2-1.jpg', '/images/flat2-2.jpg', '/images/flat2-3.jpg'], '/images/flat2-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', 'per_month', 'part_furnished', '2024-01-15', 12, 350000),

('sale', 'active', 'Elegant 3-Bedroom Mansion Flat in Maida Vale', 'Beautiful period conversion in white stucco mansion block. Three bedrooms, period features, high ceilings, communal gardens. Located on tree-lined avenue close to Little Venice canals.', 145000000, 'offers_over', 'flat', 3, 2, 1, 1200, 'Flat 2, 45 Maida Avenue', '', 'W2 1TH', 2, 'leasehold', 'E', 'D', 1900, ARRAY['period_features', 'high_ceilings', 'communal_gardens', 'wooden_floors'], ARRAY['Little Venice', 'Maida Vale Station', 'Canal walks', 'Local restaurants'], ARRAY['/images/flat3-1.jpg', '/images/flat3-2.jpg', '/images/flat3-3.jpg'], '/images/flat3-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', NULL, NULL, NULL, NULL, NULL),

('rental', 'active', 'Modern 2-Bedroom Flat in Queens Park', 'Contemporary apartment in purpose-built development. Two double bedrooms, open-plan living, private balcony, parking space. Close to Queens Park and excellent local schools.', 285000, NULL, 'flat', 2, 2, 1, 750, 'Apartment 8, The Quadrant', 'Salusbury Road', 'NW6 6RG', 4, 'leasehold', 'D', 'B', 2015, ARRAY['balcony', 'parking', 'modern_kitchen', 'ensuite_bathroom', 'lift'], ARRAY['Queens Park Station', 'Local schools', 'Salusbury Road shops', 'Brondesbury Park'], ARRAY['/images/flat4-1.jpg', '/images/flat4-2.jpg', '/images/flat4-3.jpg'], '/images/flat4-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', 'per_month', 'unfurnished', '2024-03-01', 12, 570000),

('sale', 'active', 'Converted 1-Bedroom Loft Apartment in Ladbroke Grove', 'Unique loft-style apartment in converted warehouse. Industrial features, exposed brick, mezzanine bedroom, roof terrace access. Close to Portobello Market and vibrant local scene.', 78500000, 'guide_price', 'flat', 1, 1, 1, 650, 'Unit 12, The Warehouse', 'Golborne Road', 'W10 5NW', 7, 'leasehold', 'D', 'C', 2010, ARRAY['roof_terrace', 'exposed_brick', 'high_ceilings', 'unique_character', 'mezzanine'], ARRAY['Portobello Market', 'Ladbroke Grove Station', 'Local pubs', 'Golborne Road'], ARRAY['/images/flat5-1.jpg', '/images/flat5-2.jpg', '/images/flat5-3.jpg'], '/images/flat5-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', NULL, NULL, NULL, NULL, NULL);

-- COMMERCIAL PROPERTIES (5)
INSERT INTO properties (listing_type, status, title, description, price, price_qualifier, property_type, bedrooms, bathrooms, receptions, square_footage, address_line1, address_line2, postcode, area_id, tenure, council_tax_band, energy_rating, year_built, features, amenities, images, floor_plan, viewing_arrangements, agent_contact, rent_period, furnished, available_from, minimum_tenancy, deposit) VALUES

('sale', 'active', 'Prime Retail Unit on Kilburn High Road', 'Prominent retail premises with excellent footfall on busy Kilburn High Road. Ground floor retail with storage basement. Suitable for various retail uses. Strong rental potential in developing area.', 89500000, 'guide_price', 'commercial', 0, 2, 0, 1200, '156-158 Kilburn High Road', '', 'NW6 4JD', 5, 'freehold', NULL, 'C', 1920, ARRAY['high_street_location', 'storage_basement', 'prominent_frontage', 'excellent_footfall'], ARRAY['Kilburn Station', 'Bus routes', 'High street location', 'Parking nearby'], ARRAY['/images/commercial1-1.jpg', '/images/commercial1-2.jpg', '/images/commercial1-3.jpg'], '/images/commercial1-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', NULL, NULL, NULL, NULL, NULL),

('rental', 'active', 'Modern Office Space in Bayswater', 'Contemporary office accommodation in prestigious Bayswater location. Open-plan layout, modern facilities, excellent natural light. Perfect for creative or professional services business.', 850000, NULL, 'commercial', 0, 3, 0, 2500, 'Second Floor, 88 Westbourne Grove', '', 'W2 5RT', 1, 'leasehold', NULL, 'B', 2005, ARRAY['air_conditioning', 'lift', 'modern_facilities', 'excellent_natural_light'], ARRAY['Bayswater Station', 'Westbourne Grove shops', 'Hyde Park nearby', 'Restaurants'], ARRAY['/images/commercial2-1.jpg', '/images/commercial2-2.jpg', '/images/commercial2-3.jpg'], '/images/commercial2-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', 'per_month', 'unfurnished', '2024-02-15', 36, 2550000),

('sale', 'active', 'Investment Opportunity - Restaurant Premises in Queens Park', 'Established restaurant with full commercial kitchen, seating for 50, and external seating area. Long lease in place with good covenant tenant. Strong investment yield in popular dining location.', 165000000, 'offers_invited', 'commercial', 0, 4, 0, 1800, 'The Corner Restaurant', '2-4 Salusbury Road', 'NW6 6NN', 4, 'leasehold', NULL, 'C', 1910, ARRAY['commercial_kitchen', 'external_seating', 'established_business', 'good_covenant_tenant'], ARRAY['Queens Park Station', 'Salusbury Road shops', 'Local community', 'Evening economy'], ARRAY['/images/commercial3-1.jpg', '/images/commercial3-2.jpg', '/images/commercial3-3.jpg'], '/images/commercial3-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', NULL, NULL, NULL, NULL, NULL),

('rental', 'active', 'Creative Studio Space in Kensal Green', 'Flexible studio space in converted industrial building. High ceilings, excellent natural light, loading access. Suitable for creative industries, storage, or light industrial use.', 425000, NULL, 'commercial', 0, 2, 0, 3000, 'Unit 7, Kensal Works', 'Ladbroke Grove', 'NW10 6BJ', 6, 'leasehold', NULL, 'D', 1950, ARRAY['high_ceilings', 'loading_access', 'flexible_space', 'industrial_character'], ARRAY['Kensal Green Station', 'Creative community', 'Canal nearby', 'Good transport links'], ARRAY['/images/commercial4-1.jpg', '/images/commercial4-2.jpg', '/images/commercial4-3.jpg'], '/images/commercial4-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', 'per_month', 'unfurnished', '2024-01-20', 24, 1275000),

('sale', 'active', 'Medical Suite in St Johns Wood', 'Purpose-built medical centre with 6 consulting rooms, reception area, and parking. Fully fitted with medical facilities. Prime location near medical district with excellent accessibility.', 285000000, 'guide_price', 'commercial', 0, 6, 1, 2200, 'The Medical Centre', 'Wellington Road', 'NW8 9SX', 3, 'freehold', NULL, 'B', 1995, ARRAY['medical_facilities', 'parking', 'consulting_rooms', 'disabled_access'], ARRAY['St Johns Wood Station', 'Medical district', 'Excellent accessibility', 'Professional area'], ARRAY['/images/commercial5-1.jpg', '/images/commercial5-2.jpg', '/images/commercial5-3.jpg'], '/images/commercial5-floorplan.jpg', 'by_appointment', 'Catwalk Frames - 020 7946 0958', NULL, NULL, NULL, NULL, NULL);

-- Update the rental properties with the correct rental-specific fields
UPDATE properties SET
    rent_period = 'per_month',
    minimum_tenancy = 12,
    deposit = 1300000
WHERE address_line1 = '67 Clifton Gardens';

-- Query to verify the data was inserted correctly
SELECT
    la.name as area_name,
    la.postcode,
    COUNT(p.id) as property_count,
    COUNT(CASE WHEN p.property_type = 'house' THEN 1 END) as houses,
    COUNT(CASE WHEN p.property_type = 'flat' THEN 1 END) as flats,
    COUNT(CASE WHEN p.property_type = 'commercial' THEN 1 END) as commercial
FROM london_areas la
LEFT JOIN properties p ON la.id = p.area_id
GROUP BY la.id, la.name, la.postcode
ORDER BY la.name;